"""Aggregate benchmark shards into docs-ready results + a blind human-rating sheet.

  python tools/ci/bench_report.py --results DIR --out DIR

Produces:
  BENCHMARK_AUTO.md        automatic metrics only (chrF++, deterministic error flags, latency, memory)
  per_case.jsonl           every case with outputs of all models and flags
  blind_sheet.csv          shuffled, anonymised (System A/B) sheet for expert rating per EVAL_RUBRIC.md
  blind_key.json           mapping A/B -> model (keep away from raters until scoring is done)
Automatic metrics do NOT decide the winner (docs/EVAL_RUBRIC.md §5).
"""
from __future__ import annotations

import argparse
import csv
import json
import random
import statistics
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from arabica.glossary import normalize  # noqa: E402
from arabica.linguistics import canonical_numbers, dialect_markers, inferred_language, negation_count  # noqa: E402


def chrf(hyps: list[str], refs: list[str]) -> float | None:
    try:
        from sacrebleu.metrics import CHRF
    except ImportError:
        return None
    if not hyps:
        return None
    return round(CHRF(word_order=2).corpus_score(hyps, [refs]).score, 2)


def flags(case: dict, out: str | None) -> list[str]:
    if not out:
        return ["no_output"]
    f = []
    d = case["direction"]
    src_l, tgt_l = ("ru", "ar") if d == "ru-ar" else ("ar", "ru")
    if sorted(canonical_numbers(case["source"])) != sorted(canonical_numbers(out)):
        f.append("numbers")
    lexical_note = "отрицан" in case.get("note", "")
    if not lexical_note and (negation_count(case["source"], src_l) > 0) != (negation_count(out, tgt_l) > 0):
        f.append("negation")
    for m in case["checks"]["must_contain"]:
        if normalize(m, tgt_l) not in normalize(out, tgt_l):
            f.append("must_contain")
            break
    lang = inferred_language(out)
    if lang not in (tgt_l, "mixed", "unknown"):
        f.append("wrong_language")
    if "<think>" in out or "</think>" in out:
        f.append("reasoning_leak")
    if tgt_l == "ar" and dialect_markers(out):
        f.append("dialect")
    if not case["checks"]["short_input"] and len(case["source"]) > 40:
        ratio = len(out) / max(1, len(case["source"]))
        if ratio < 0.4 or ratio > 2.8:
            f.append("length_ratio")
    return f


def pct(v: list[float], q: float) -> float:
    v = sorted(v)
    return round(v[min(len(v) - 1, int(q * (len(v) - 1) + 0.5))], 1) if v else 0.0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--seed", type=int, default=20261009)
    a = ap.parse_args()
    res_dir, out = Path(a.results), Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    cases = {c["id"]: c for c in (json.loads(l) for l in
             (ROOT / "docs/EVAL_CASES.jsonl").read_text(encoding="utf-8").splitlines() if l)}
    results: dict[str, dict[str, dict]] = defaultdict(dict)
    metas: dict[str, list[dict]] = defaultdict(list)
    for p in res_dir.rglob("results-*.jsonl"):
        for line in p.read_text(encoding="utf-8").splitlines():
            if line.strip():
                r = json.loads(line)
                results[r["model"]][r["id"]] = r
    for p in res_dir.rglob("bench-*.json"):
        m = json.loads(p.read_text(encoding="utf-8"))
        metas[m["model"]].append(m)
    models = sorted(results)
    L = ["# Benchmark — automatic metrics (NOT a final verdict)", "",
         "Generated by `tools/ci/bench_report.py` from real CPU runs on a GitHub Windows runner.",
         "Expert blind rating (EVAL_RUBRIC.md) is required before choosing a model.", ""]
    L.append("| Model | cases with output | errors | peak RAM (GB) | cold start (s) | sec/case p50 | p95 |")
    L.append("|---|---|---|---|---|---|---|")
    for m in models:
        rs = list(results[m].values())
        secs = [r["seconds"] for r in rs if r.get("output")]
        peak = max((x.get("peak_rss_bytes", 0) for x in metas[m]), default=0) / 1e9
        cold = max((x.get("cold_start_s", 0) for x in metas[m]), default=0)
        L.append(f"| {m} | {sum(1 for r in rs if r.get('output'))}/{len(cases)} | "
                 f"{sum(1 for r in rs if r.get('error'))} | {peak:.1f} | {cold} | {pct(secs, .5)} | {pct(secs, .95)} |")
    hosts = {json.dumps(x.get("host"), sort_keys=True) for v in metas.values() for x in v}
    L += ["", "Hosts: " + "; ".join(sorted(hosts)), ""]
    per_case = []
    for d in ("ru-ar", "ar-ru"):
        L += [f"## {d}", "", "| Category | " + " | ".join(f"{m} chrF++ | {m} flagged" for m in models) + " |",
              "|---|" + "---|---|" * len(models)]
        cats = sorted({c["category"] for c in cases.values() if c["direction"] == d})
        for cat in cats + ["ALL"]:
            ids = [i for i, c in cases.items() if c["direction"] == d and (cat == "ALL" or c["category"] == cat)]
            row = [cat]
            for m in models:
                pairs = [(results[m][i].get("output") or "", cases[i]["reference"]) for i in ids if i in results[m]]
                score = chrf([p[0] for p in pairs], [p[1] for p in pairs])
                fl = sum(1 for i in ids if i in results[m] and flags(cases[i], results[m][i].get("output")))
                row += [str(score), f"{fl}/{len(ids)}"]
            L.append("| " + " | ".join(row) + " |")
        L.append("")
    L += ["## Deterministic error flags (counts)", "", "| Flag | " + " | ".join(models) + " |",
          "|---|" + "---|" * len(models)]
    counts = {m: defaultdict(int) for m in models}
    for i, c in cases.items():
        row = {"id": i, "direction": c["direction"], "category": c["category"], "level": c["level"],
               "source": c["source"], "reference": c["reference"], "outputs": {}}
        for m in models:
            r = results[m].get(i, {})
            fl = flags(c, r.get("output"))
            for x in fl:
                counts[m][x] += 1
            row["outputs"][m] = {"text": r.get("output"), "error": r.get("error"), "flags": fl,
                                 "seconds": r.get("seconds"), "mode": r.get("mode")}
        per_case.append(row)
    for flag in sorted({f for m in models for f in counts[m]}):
        L.append(f"| {flag} | " + " | ".join(str(counts[m][flag]) for m in models) + " |")
    L += ["", "Flags are heuristic triggers for review, not proven errors (see LINGUISTIC_CONTRACT.md §6)."]
    (out / "BENCHMARK_AUTO.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    (out / "per_case.jsonl").write_text("\n".join(json.dumps(r, ensure_ascii=False) for r in per_case) + "\n",
                                        encoding="utf-8")
    # blind sheet
    rnd = random.Random(a.seed)
    key = {}
    with (out / "blind_sheet.csv").open("w", encoding="utf-8-sig", newline="") as f:
        w = csv.writer(f)
        w.writerow(["item", "case_id", "direction", "category", "source", "reference", "system", "translation",
                    "adequacy_1_5", "fluency_1_5", "terminology_1_5", "worst_error_severity", "error_types",
                    "omissions_additions", "comment"])
        items = []
        for row in per_case:
            labels = ["A", "B", "C"][:len(models)]
            order = models[:]
            rnd.shuffle(order)
            for lab, m in zip(labels, order):
                items.append((row, lab, m))
        rnd.shuffle(items)
        for n, (row, lab, m) in enumerate(items, 1):
            key[str(n)] = {"case_id": row["id"], "system": lab, "model": m}
            w.writerow([n, row["id"], row["direction"], row["category"], row["source"], row["reference"], lab,
                        row["outputs"][m]["text"] or "", "", "", "", "", "", "", ""])
    (out / "blind_key.json").write_text(json.dumps(key, indent=1), encoding="utf-8")
    print("\n".join(L))
    return 0


if __name__ == "__main__":
    sys.exit(main())
